server:
  port: 9007

spring:
  application:
    name: meal-service
  datasource:
    url: jdbc:postgresql://localhost:5432/meal_db
    username: postgres
    password: 98534323
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter: DEBUG

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


